In [1]:
import torch
import numpy as np

In [2]:
a=torch.ones(3)
print(a)

tensor([1., 1., 1.])


In [3]:
a[2]=17
a

tensor([ 1.,  1., 17.])

In [5]:
b=[4.0, 1.0, 5.0, 3.0, 2.0, 1.0]
b_t=torch.tensor(b) # t denotes torch tensor
b_t

tensor([4., 1., 5., 3., 2., 1.])

In [8]:

c=[[4.0, 1.0], [5.0, 3.0], [2.0, 1.0]]
c_t=torch.tensor(c)
print(c_t.shape)

torch.Size([3, 2])


In [7]:
d_t=torch.zeros(3, 2)
print(d_t)

tensor([[0., 0.],
        [0., 0.],
        [0., 0.]])


In [9]:
d_t[0,1]=17 #sets this value to 17
d_t[1,1]=14 #sets this value to 14
d_t #prints everything


tensor([[ 0., 17.],
        [ 0., 14.],
        [ 0.,  0.]])

In [10]:
#slice out the second row only
d_t[1]

tensor([ 0., 14.])

In [11]:
#turn a matrix from a 2D matrix into a 3D matrix
#can be used when malong a multiplication of one tensor to another tensor
#print out the shape first
d_t.shape

torch.Size([3, 2])

In [12]:
#three dots means we are creating a new dimension and for it to figure it out, we are creating a new dimension named "None"
d_t_unsqueeze =d_t[...,None]
d_t_unsqueeze.shape 
#you can also move it to the other size by putting d_t[None, ...] which would put th enew dimension agead fo the other ones

torch.Size([3, 2, 1])

In [13]:
# a tensor with 4 dimension, to assume we have images in color and we will feed batches of a certain size into our ML
batch_t=torch.randn(2, 3, 32, 32) #randn gives random numbers
#batch_t=torch.randn(# batches (samples), channels for RGB, size of grid in rows (32), columns(32)
## we want to do it in batches so we do not overun the RAM, the more comuputing power you have the larger these can be
batch_t.shape

torch.Size([2, 3, 32, 32])

In [14]:
double_points=torch.ones(10,2, dtype=torch.double)
double_points.dtype
# data type is important in this

torch.float64

In [16]:
#numpy has interoperability meaning going from a torch tensor to a numpy something quickly to quantify performance,
#sklearn would be easier to use in this instance of visual performance, but sklearn only works with numpy so you would go from torch to numpy
#to go from torch to numpy:
points=torch.ones(3, 4)
points 

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [17]:
points_np= points.numpy() #np to remind you it is a numpy array
points_np
#you can see below that it is now an array instead of a tensor

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]], dtype=float32)

In [18]:
#to go back to a tensor:
points_t=torch.from_numpy(points_np)
points_t
#notice it is now a tensor again

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])